# Generated by Django 5.1.1 on 2024-10-15 17:38

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(max_length=700, upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
